# Generated by Django 5.0.2 on 2024-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='netelement',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Продукты'),
        ),
    ]
