# Generated by Django 5.0.2 on 2024-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_netelement_products'),
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netelement',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product', verbose_name='Продукты'),
        ),
    ]
