# Generated by Django 5.0.2 on 2024-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_alter_netelement_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netelement',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
