# Generated by Django 5.0.2 on 2024-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
